name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push
        run: echo "Build and push docker image"
      - name: Deploy
        run: echo "Deploy to production"
